### ISSUE TITLE
DirectXShaderCompiler vendored in SDL_shadercross fails to build with Xcode 26.4 / Apple clang 21 on macOS

### ISSUE THREAD

**Issue by tsukinoko-kun** [libsdl-org/SDL_shadercross#199]
Hi,
I am hitting a build failure in the vendored external/DirectXShaderCompiler when building shadercross on macOS with current Xcode.
Environment:
- macOS on Apple Silicon
- Xcode 26.4
- Apple clang 21.0.0
- SDK: MacOSX26.4.sdk
- SDL_shadercross [3a31448](https://github.com/libsdl-org/SDL_shadercross/commit/3a314481ede01f5d966f0e834019942e34c02b82)

I have SDL_shadercross vendored in my game engine. The build fails while compiling vendor/SDL_shadercross/external/DirectXShaderCompiler/... sources, with errors coming from include/llvm/ADT/StringRef.h.
Representative error:
```
/Users/frank/Projects/bms/adventurer/vendor/SDL_shadercross/external/DirectXShaderCompiler/include/llvm/ADT/StringRef.h:579:10: error: 'is_nothrow_constructible' cannot be specialized: Users are not allowed to specialize this standard library entity [-Winvalid-specialization]
  579 |   struct is_nothrow_constructible <std::string, llvm::StringRef>
      |          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.4.sdk/usr/include/c++/v1/__type_traits/is_nothrow_constructible.h:23:8: note: marked '_Clang::no_specializations' here
   23 | struct _LIBCPP_NO_SPECIALIZATIONS is_nothrow_constructible
      | 
```
I see the same error for:
- is_nothrow_constructible<std::string, llvm::StringRef>
- is_nothrow_constructible<std::string, llvm::StringRef &>
- is_nothrow_constructible<std::string, const llvm::StringRef &>
This appears to be caused by newer libc++ in Xcode 26.4 rejecting specialization of this standard library trait.

Full log: https://pastebin.com/XKX67V5N

**Comment by madebr** [comment]
Does bumping DirectXShaderCompiler to the latest release fix your compiler issue?

**Comment by tsukinoko-kun** [comment]
> Does bumping DirectXShaderCompiler to the latest release fix your compiler issue?

No. But I fixed the issue upstream and opened a PR

https://github.com/microsoft/DirectXShaderCompiler/pull/8307

I use the patched version in my engine now, and it works.

**Comment by tsukinoko-kun** [comment]
If my PR gets merged by Microsoft, I will PR to SDLs fork of DirectXShaderCompiler and then to SDL_shadercross.

If someone needs it working right now, my patched version is available.

**Comment by tsukinoko-kun** [comment]
**Maintainer help needed**

My PR got merged by Microsoft. But I can't PR that into the SDL fork of DirectXShaderCompiler, nor can I create an issue there.

Can a maintainer please update the SDL fork of DirectXShaderCompiler to the latest upstream version and update the submodule in SDL_shadercross?

The PR I am talking about: https://github.com/microsoft/DirectXShaderCompiler/pull/8307

**Comment by madebr** [comment]
See https://github.com/libsdl-org/SDL_shadercross/pull/209. Once ci is green, it will be merged.

Thanks for your work!
